# -*- mode: ruby -*-
# vi: set ft=ruby :

## Rename this to Vagrantfile to have 'vagrant up' work properly

###32bit Debian 9 Vagrant VM
### for EmptyEpsilon https://github.com/daid/EmptyEpsilon
### By Kwadroke "of The Wired" https://github.com/kwadroke

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/bionic64"
  config.env.enable         # Enable vagrant-env(.env)
  config.ssh.forward_x11 = true
  config.ssh.insert_key = false
  config.vm.provider "virtualbox" do |vb|
    vb.cpus = 4
    vb.memory = 4096
  end
  config.vm.synced_folder ENV['EMPTY_EPSILON'], "/EmptyEpsilon", id: "ee"
  config.vm.synced_folder ENV['SERIOUS_PROTON'], "/SeriousProton", id: "sp"
  config.vm.synced_folder ENV['RELEASE'], "/release", id: "r"
  config.vm.provision :shell, path: "build_ee_u1804.sh", run: 'always'
  config.vm.hostname = "bridgesim-ee"
end
